services:
  # Redis
  redis:
    image: redis:7-alpine
    container_name: stock_alerting_redis
    ports:
      - "6379:6379"
    networks:
      - stock_alerting_network
    volumes:
      - redis_data:/data

  # Django Backend
  backend:
    build: .
    container_name: stock_alerting_backend
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - stock_alerting_network

  # Celery Worker
  celery:
    build: .
    container_name: stock_alerting_celery
    command: celery -A stock_alerting worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    networks:
      - stock_alerting_network

  # Celery Beat (Scheduler)
  celery-beat:
    build: .
    container_name: stock_alerting_celery_beat
    command: celery -A stock_alerting beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend
    networks:
      - stock_alerting_network

volumes:
  redis_data:
  static_volume:
  media_volume:

networks:
  stock_alerting_network:
    driver: bridge
