# Generated by Django 4.2.7 on 2025-08-06 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Alert"),
                            ("duration", "Duration Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("above", "Above"), ("below", "Below")], max_length=10
                    ),
                ),
                (
                    "threshold_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True, help_text="Required for duration alerts", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("condition_first_met", models.DateTimeField(blank=True, null=True)),
                ("condition_currently_met", models.BooleanField(default=False)),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="stocks.stock",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("threshold", "Threshold Alert"),
                            ("duration", "Duration Alert"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("html_content", models.TextField()),
                ("text_content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TriggeredAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("notification_error", models.TextField(blank=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triggered_instances",
                        to="alerts.alert",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
