# Generated by Django 4.2.7 on 2025-08-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Required for duration alerts (minimum 1 minute)",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["is_active", "stock"], name="alert_active_stock_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["user", "is_active"], name="alert_user_active_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="alert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user", "stock", "alert_type", "condition", "threshold_price"),
                name="unique_active_alert_per_user_stock_condition",
            ),
        ),
    ]
