# Generated by Django 4.2.7 on 2025-08-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alter_alert_duration_minutes_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotificationTemplate",
        ),
    ]
