# Generated by Django 4.2.7 on 2025-08-12 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_current_price_stock_last_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIRequestLog',
        ),
    ]
